# Pre made config: https://github.com/omerxx/dotfiles

# Update tmux config cmd: tmux source-file ~/.tmux.conf
unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

# Move panes with vim movement
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Adds mouse support in tmux
set -g mouse on

# set-option -g status-position top

# Makes tmux's copy/scroll mode use Vim-style keybindings.
# set-window-option -g mode-keys vi

# tpm (Tmux Plugin Manager) - installed here: /home/frederickd/.tmux/plugins/tpm
# Install tpm: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator' # https://github.com/christoomey/vim-tmux-navigator - Don't forget to add plugin to nvim
set -g @plugin 'catppuccin/tmux'

# Initialize TPM (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
# Update plugins: Ctrl+b -> Shift+i
