# Update tmux config cmd: tmux source-file ~/.tmux.conf

set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
# set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
# set -g status-position top       # macOS / darwin style
# set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g mouse on
bind | split-window -h -p 30 # Vertical split 30% window

# Vim-style pane navigation
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

# Plugins
# set -g @plugin 'christoomey/vim-tmux-navigator' # nvim switch between panes
